# Generated by Django 5.1.6 on 2025-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_specialty_alter_doctors_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='users/profiles/patient1.jpg', upload_to='users/profiles'),
        ),
    ]
