# Generated by Django 5.1.6 on 2025-03-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_users_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='patient1.jpg', upload_to='users/profiles'),
        ),
    ]
