# Generated by Django 5.1.6 on 2025-03-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_users_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default='patient1.jpg', upload_to=''),
        ),
    ]
